---
- hosts: master
  become: true
  remote_user: root

  vars:

  tasks:
  - name: Disable SWAP
    shell: |
      swapoff -a

  - name: Remove SWAP from fstab
    mount:
      name: swap
      fstype: swap
      state: absent
  
  # - name: Permanently set SELINUX to permissive
  #   selinux:
  #     policy: targeted
  #     state: permissive

  - name: Setting sebool container_manage_cgroup
    seboolean:
      name: container_manage_cgroup
      state: yes
      persistent: yes

  - name: firewalld port 6443 (API server)
    firewalld:
      port: 6443/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: firewalld port 2379-2380 (ETCD)
    firewalld:
      port: 2379-2380/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: firewalld port 10250 (Kubelet API)
    firewalld:
      port: 10250/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: firewalld port 10251 (kube-scheduler)
    firewalld:
      port: 10251/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: firewalld port 10252 (kube-controller-manager)
    firewalld:
      port: 10252/tcp
      permanent: yes
      immediate: yes
      state: enabled

  - name: Enable firewalld masquerading
    firewalld:
      masquerade: yes
      permanent: true
      immediate: yes
      state: enabled

  - name: Modprobe br_netfilter to set sysctls
    modprobe:
      name: br_netfilter
      state: present

  - name: Set sysctl bridge.bridge-nf-call-ip6tables
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: '1'
      sysctl_file: /etc/sysctl.d/k8s.conf
      sysctl_set: yes
      reload: yes

  - name: Set sysctl bridge.bridge-nf-call-iptables
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: '1'
      sysctl_file: /etc/sysctl.d/k8s.conf
      sysctl_set: yes
      reload: yes

  - name: Set sysctl net.ipv4.ip_forward
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      sysctl_file: /etc/sysctl.d/k8s.conf
      sysctl_set: yes
      reload: yes

  - name: Disable IPv6 (Optional)
    sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: '1'
      sysctl_file: /etc/sysctl.d/k8s.conf
      sysctl_set: yes
      reload: yes

  - name: Enable kubeadm repo
    yum_repository:
      name: kubernetes
      description: Kubernetes
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      repo_gpgcheck: yes
      gpgcheck: yes
      gpgkey:
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install kubeadm, kubectl & kubelet
    dnf:
      name:
        - kubeadm
        - kubectl
        - kubelet
      disable_excludes: kubernetes
      state: present

  - name: Enable kubelet
    systemd:
      name: kubelet
      state: started
      enabled: yes

  - name: Enable cgroup driver
    copy:
      dest: /etc/sysconfig/kubelet
      content: |
        KUBELET_EXTRA_ARGS=--feature-gates="AllAlpha=false,RunAsGroup=true" --container-runtime=remote --cgroup-driver=systemd --container-runtime-endpoint='unix:///var/run/crio/crio.sock' --runtime-request-timeout=5m

  - name: Restart kubelet
    systemd:
      daemon_reload: yes
      name: kubelet
      state: restarted
