---
apiVersion: v1
kind: Namespace
metadata:
    name: sample-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-deployment
  namespace: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: sample-app
  labels:
    app: sample-app
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: sample-app

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-app-ingress
  namespace: sample-app
  labels:
    app: sample-app
spec:
  rules:
  - host: sample-app.localdomain
    http:
      paths:
      - path: /
        backend:
          serviceName: testapp-service
          servicePort: 8080
